# Generated by Django 6.0.7 on 2026-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_liv_area', models.IntegerField()),
                ('lot_area', models.IntegerField()),
                ('bedroom_abv_gr', models.IntegerField()),
                ('full_bath', models.IntegerField()),
                ('garage_cars', models.FloatField()),
                ('garage_area', models.FloatField()),
                ('total_bsmt_sf', models.FloatField()),
                ('fireplaces', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('overall_qual', models.IntegerField()),
                ('overall_cond', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=100)),
                ('central_air', models.CharField(max_length=10)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
